-- ==============================
-- IKYA GIG WORKERS APP DATABASE
-- PostgreSQL schema for mobile income tracking + prediction
-- ==============================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Reusable timestamp trigger for updated_at columns.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- App users. user_id can be generated by PostgreSQL or supplied by the API/auth layer.
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    has_completed_onboarding BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Gig platforms/marketplaces used by workers.
CREATE TABLE IF NOT EXISTS platforms (
    platform_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    platform_name VARCHAR(50) UNIQUE NOT NULL,
    category VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS platforms_set_updated_at ON platforms;
CREATE TRIGGER platforms_set_updated_at
BEFORE UPDATE ON platforms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Earnings records mapped to the current mobile app fields:
-- platform, amount, date, status, paymentFrequency, recordedAt.
CREATE TABLE IF NOT EXISTS earnings_records (
    record_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    platform_id BIGINT NOT NULL REFERENCES platforms(platform_id) ON DELETE RESTRICT,

    -- Optional client-side ID from the React Native app for offline sync / duplicate prevention.
    mobile_entry_id VARCHAR(80),

    record_type VARCHAR(20) NOT NULL DEFAULT 'one_time' CHECK (
        record_type IN ('daily', 'weekly', 'fortnightly', 'monthly', 'one_time', 'custom')
    ),
    payment_frequency VARCHAR(20) NOT NULL DEFAULT 'one_time' CHECK (
        payment_frequency IN ('daily', 'weekly', 'fortnightly', 'monthly', 'one_time')
    ),
    status VARCHAR(20) NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'pending')),

    date_start DATE NOT NULL,
    date_end DATE NOT NULL,
    earned_on DATE GENERATED ALWAYS AS (date_start) STORED,
    year INTEGER GENERATED ALWAYS AS (EXTRACT(YEAR FROM date_start)::INTEGER) STORED,
    month INTEGER GENERATED ALWAYS AS (EXTRACT(MONTH FROM date_start)::INTEGER) STORED,
    week_number INTEGER GENERATED ALWAYS AS (EXTRACT(WEEK FROM date_start)::INTEGER) STORED,

    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    amount_received NUMERIC(12,2) GENERATED ALWAYS AS (
        CASE WHEN status = 'received' THEN amount ELSE 0 END
    ) STORED,
    pending_amount NUMERIC(12,2) GENERATED ALWAYS AS (
        CASE WHEN status = 'pending' THEN amount ELSE 0 END
    ) STORED,

    hours_worked NUMERIC(8,2) CHECK (hours_worked IS NULL OR hours_worked >= 0),
    tasks_completed INTEGER CHECK (tasks_completed IS NULL OR tasks_completed >= 0),
    work_category VARCHAR(50),
    season VARCHAR(20),
    growth_factor NUMERIC(5,2),
    notes TEXT,

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT earnings_valid_date_range CHECK (date_end >= date_start),
    CONSTRAINT earnings_unique_mobile_entry UNIQUE (user_id, mobile_entry_id)
);

CREATE INDEX IF NOT EXISTS idx_earnings_user_date ON earnings_records(user_id, date_start DESC);
CREATE INDEX IF NOT EXISTS idx_earnings_user_status ON earnings_records(user_id, status);
CREATE INDEX IF NOT EXISTS idx_earnings_platform ON earnings_records(platform_id);
CREATE INDEX IF NOT EXISTS idx_earnings_monthly_summary ON earnings_records(user_id, year, month, platform_id);

DROP TRIGGER IF EXISTS earnings_records_set_updated_at ON earnings_records;
CREATE TRIGGER earnings_records_set_updated_at
BEFORE UPDATE ON earnings_records
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- User-level prediction preferences used by annual income projections.
CREATE TABLE IF NOT EXISTS prediction_factors (
    factor_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    projected_growth_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    planned_extra_hours NUMERIC(8,2) NOT NULL DEFAULT 0,
    new_platform_expected_income NUMERIC(12,2) NOT NULL DEFAULT 0,
    pending_realization_rate NUMERIC(5,2) NOT NULL DEFAULT 100 CHECK (
        pending_realization_rate BETWEEN 0 AND 100
    ),
    seasonal_adjustment_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    linear_extrapolation_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_prediction_factors_user_updated ON prediction_factors(user_id, updated_at DESC);

DROP TRIGGER IF EXISTS prediction_factors_set_updated_at ON prediction_factors;
CREATE TRIGGER prediction_factors_set_updated_at
BEFORE UPDATE ON prediction_factors
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Useful seed data. App/API can add more platforms at runtime.
INSERT INTO platforms (platform_name, category)
VALUES
    ('Uber', 'driving'),
    ('Lyft', 'driving'),
    ('DoorDash', 'delivery'),
    ('Instacart', 'delivery'),
    ('Fiverr', 'freelance'),
    ('Upwork', 'freelance')
ON CONFLICT (platform_name) DO UPDATE
SET category = EXCLUDED.category;

-- Monthly summary by platform for dashboard/report screens.
CREATE OR REPLACE VIEW monthly_platform_income_summary AS
SELECT
    e.user_id,
    e.platform_id,
    p.platform_name,
    e.year,
    e.month,
    SUM(e.amount_received) AS total_received,
    SUM(e.pending_amount) AS total_pending,
    SUM(e.amount) AS total_income,
    COALESCE(SUM(e.hours_worked), 0) AS total_hours,
    COALESCE(SUM(e.tasks_completed), 0) AS total_tasks,
    COUNT(*) AS record_count
FROM earnings_records e
JOIN platforms p ON p.platform_id = e.platform_id
GROUP BY e.user_id, e.platform_id, p.platform_name, e.year, e.month;

-- Pending payouts older than 30 days.
CREATE OR REPLACE VIEW pending_payments_older_than_30_days AS
SELECT
    e.user_id,
    e.record_id,
    p.platform_name,
    e.date_start,
    e.date_end,
    e.pending_amount,
    CURRENT_DATE - e.date_end AS days_overdue
FROM earnings_records e
JOIN platforms p ON p.platform_id = e.platform_id
WHERE e.status = 'pending'
  AND e.pending_amount > 0
  AND e.date_end < CURRENT_DATE - INTERVAL '30 days';

-- Annual platform totals.
CREATE OR REPLACE VIEW annual_platform_income_summary AS
SELECT
    e.user_id,
    e.platform_id,
    p.platform_name,
    e.year,
    SUM(e.amount_received) AS annual_received,
    SUM(e.pending_amount) AS annual_pending,
    AVG(e.amount_received) AS avg_received_per_record,
    COUNT(*) AS record_count
FROM earnings_records e
JOIN platforms p ON p.platform_id = e.platform_id
GROUP BY e.user_id, e.platform_id, p.platform_name, e.year;

-- Lightweight annual prediction that mirrors the app's recent-income projection idea.
CREATE OR REPLACE FUNCTION predict_annual_income(target_user_id UUID)
RETURNS TABLE (
    avg_monthly_income NUMERIC(12,2),
    projected_growth_rate NUMERIC(5,2),
    new_platform_expected_income NUMERIC(12,2),
    predicted_annual_income NUMERIC(12,2)
) AS $$
BEGIN
    RETURN QUERY
    WITH monthly_totals AS (
        SELECT
            date_trunc('month', date_start)::DATE AS income_month,
            SUM(amount_received) AS received_total
        FROM earnings_records
        WHERE user_id = target_user_id
          AND status = 'received'
          AND date_start >= CURRENT_DATE - INTERVAL '6 months'
        GROUP BY date_trunc('month', date_start)::DATE
    ),
    income_average AS (
        SELECT COALESCE(AVG(received_total), 0)::NUMERIC(12,2) AS avg_monthly
        FROM monthly_totals
    ),
    latest_factors AS (
        SELECT
            pf.projected_growth_rate,
            pf.new_platform_expected_income
        FROM prediction_factors pf
        WHERE pf.user_id = target_user_id
        ORDER BY pf.updated_at DESC
        LIMIT 1
    )
    SELECT
        ia.avg_monthly,
        COALESCE(lf.projected_growth_rate, 0)::NUMERIC(5,2),
        COALESCE(lf.new_platform_expected_income, 0)::NUMERIC(12,2),
        ROUND(
            ((ia.avg_monthly * 12) * (1 + COALESCE(lf.projected_growth_rate, 0) / 100))
            + COALESCE(lf.new_platform_expected_income, 0),
            2
        )::NUMERIC(12,2)
    FROM income_average ia
    LEFT JOIN latest_factors lf ON TRUE;
END;
$$ LANGUAGE plpgsql STABLE;

COMMIT;
